# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.preferredAction", 2);
